# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 00:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2017, 7, 10, 0, 39, 20, 159000, tzinfo=utc))),
                ('approve_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='post.Post')),
            ],
        ),
    ]
