# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 01:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20170709_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approve_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 10, 1, 12, 59, 960000, tzinfo=utc)),
        ),
    ]
