# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 02:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20170710_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 12, 2, 55, 59, 95000, tzinfo=utc)),
        ),
    ]
