# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'permissions': set([('can_post', 'Can post in group')])},
        ),
    ]
