# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'permissions': (('can_post', ' You can post'),)},
        ),
    ]
