# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20170717_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'permissions': (('can_post', ' You can post'), ('can_delete', 'Admin can delete group'))},
        ),
    ]
