# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20170716_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='groupmember',
            options={'permissions': (('can_post', 'Can post in group'),)},
        ),
    ]
