# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20170716_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmember',
            options={},
        ),
    ]
