# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20170717_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'permissions': (('can_post', 'You can post'),)},
        ),
    ]
